[package]
name = "desktop"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full", "rt-multi-thread", "sync", "time"] }
anyhow = "1.0"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
walkdir = "2.5"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4"] }
pathdiff = "0.2"

# Pinpath libraries
pinpath-core = { path = "../../../libs/core" }
pinpath-parser = { path = "../../../libs/parser" }
pinpath-diff = { path = "../../../libs/diff" }
tauri-plugin-dialog = "2.3.2"
notify.workspace = true
tauri-plugin-os = "2.3.0"

[target."cfg(target_os = \"macos\")".dependencies]
cocoa = "0.26"

